version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zohodevops
      MYSQL_USER: salman
      MYSQL_PASSWORD: Login14ms
    ports: 
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports: 
      - 8082:8080

volumes:
  mysql_data:
    driver: local
